import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import ReduxProvider from "@/lib/ReduxProvider";
import AuthProvider from "@/components/AuthProvider";
import { ToastProvider } from "@/components/Toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pizza Hut",
  description: "Generated by Mohamed AbuHamida",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased selection:bg-[#EE3A43] selection:text-white bg-[#f7fafe]`}
      >
        <ToastProvider />
        <ReduxProvider>
          <AuthProvider />
          <NavBar />
          {children}

          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
